### ISSUE TITLE
Github repository is existing, and the tokens are valid.

### ISSUE THREAD

**Issue by lokiixczz** [Konstanius/MineCICD#1]
Hi! I always get an issue. It seems like MineCICD cant locate my repository it always 
`Error checking out branch: repository not found`

[Screenshot](https://imgur.com/a/35hGHWi)
[Config Screenshot](https://imgur.com/a/pVRF9jM)

Please respond thank you!

**Comment by Konstanius** [comment]
The command output you're getting means that the local repository has not yet been initialized. This does not matter, which is noticeable since the line directly after that in the command output says "You might still be able to continue using the plugin", since the /cicd clone command will initialize it, similar to using git in a normal environment.

**Comment by lokiixczz** [comment]
Hi there thanks for your reply

So after that I successfully connected to my repository. But the thing is
whenever i add /git add files on my repository it does not appear on my
repo. It just add the commit message on my repository but no files. I had
check personal token permission and i did set it up correctly.

**Comment by lokiixczz** [comment]
Hi im sorry for the late reply. So I was able to update it and it seems
like when i git add my files it doesnt really upload the files to the
repository.

Thanks.

**Comment by Lorias-Jak** [comment]
Hey, we have the same bug. 
It says it uploaded the files and nothing on the repo changes. In other direction, if i pull files from repo, it doesnt applies on the server. I cant find it in the repo folder

**Comment by Konstanius** [comment]
Please both of you download the latest version, and share your `/minecicd debug` pastes.
Also share your server jar, version, and operating system.

**Comment by Lorias-Jak** [comment]
git-paper 1.19.4-533
java 17
debian 10
debug paste: https://mclo.gs/caRVqbh

im on latest version 1.3-Release

**Comment by Konstanius** [comment]
I'm sorry i made a mistake with the plugins debug command, please invalidate your github token and refresh it.

It will be omitted from the next update forward

**Comment by Lorias-Jak** [comment]
Its okay, its deleted now. Thank you for letting me know

**Comment by Konstanius** [comment]
Otherwise based on the debug command, can you please check the entire console log for any errors produced by the plugin, and can you do /minecicd reload and check if that produces any errors.

**Comment by Lorias-Jak** [comment]
<img width="568" alt="image" src="https://github.com/Konstanius/MineCICD/assets/62625225/fa6c713f-4e58-4472-8c05-1fb552dcdda4">
on startup


<img width="569" alt="image" src="https://github.com/Konstanius/MineCICD/assets/62625225/45f6030a-fb8d-45fe-b826-42eb4d514132">
on reload


<img width="572" alt="image" src="https://github.com/Konstanius/MineCICD/assets/62625225/61053eea-d2c0-442f-a93f-ea13b9338f92">
on pull (didnt saw the issue until now)

no issue on pull, but it doesnt come up on github


<img width="600" alt="image" src="https://github.com/Konstanius/MineCICD/assets/62625225/56d45c2a-158e-480d-af04-8140a06c2877">
when i use clone command, but all files show up in rep folder

**Comment by Lorias-Jak** [comment]
unfortunately I have to go to sleep now too, I'm going on vacation for a week tomorrow. Can unfortunately only answer again afterwards. I will look in here again when I'm back, so long I will unfortunately nothing can test

**Comment by Konstanius** [comment]
First, but not relevant to this discussion, issue is, that your 8080 port is already used by something, you can find this out using the `netstat` command on Linux. You can also just change the port to something that is not in use.

The other issue appears to be something deeper, I will look into that.

**Comment by Lorias-Jak** [comment]
Im back alive!

Ahhh i know whats on port 8080, thats a good call, thank you. I'll change it in minecicd soon

found something on the other issue?

**Comment by Konstanius** [comment]
I am still investigating, but it seems more and more obscure as I progress.

I think it might as well have to do with file permissions per your host.
Could you give me some insight on:
- your host
- the environment you are hosting in
- whether you can host the server and use the plugin on your own linux machine with `chmod -R 777` on the entire server directory

**Comment by Lorias-Jak** [comment]
I host at Hetzner, I'm using debian and even with the rekursive set 777 perm it does not work and the errors appear in the console

**Comment by Konstanius** [comment]
Since the repo clone command does successfully clone some / most of the files into the local repository, I assume there is limited functionality? So what happens if you try to use the plugin in a normal use case, by just modifying some files in GitHub and then pulling the changes.

**Comment by Lorias-Jak** [comment]
It wont pull the changes, there is still an error and nothing changes. I need to clone the repo again and then the changes are there

**Comment by JamesBacon** [comment]
Hey, sorry to post on such an old issue, but I'm also having the same problem. What would be sufficient information to post to help remedy it?
Errors are:
[01:42:35 INFO]: [MineCICD] Error checking out branch: repository not found: /home/minecraft/minecraft/plugins/MineCICD/repo
[MineCICD] You might still be able to continue using the plugin.

> minecicd push InitialCommit
[01:44:42 INFO]: [MineCICD] Error pushing repo: Repo folder does not exist.

**Comment by Konstanius** [comment]
> Hey, sorry to post on such an old issue, but I'm also having the same problem. What would be sufficient information to post to help remedy it? Errors are:
> 
> > [01:42:35 INFO]: [MineCICD] Error checking out branch: repository not found: /home/minecraft/minecraft/plugins/MineCICD/repo
> > [MineCICD] You might still be able to continue using the plugin.
> 
> > minecicd push InitialCommit
> > [01:44:42 INFO]: [MineCICD] Error pushing repo: Repo folder does not exist.

Could you please try to initially do ``/minecicd clone`` and then add the files you want to add using ``/minecicd add <files>``
It appears that this is a separate issue of your side and might be due to invalid usage.

I am still tracking the other issue, although progress is slow as I am barely able to spend time on it.

**Comment by Konstanius** [comment]
As information for those interested into this issue / plugin, the plugin is currently back under active development and is being rewritten in its entirety.
All issues will be fixed and marked as closed with the new release, which improves stability, compatibility, performance and enables more features.

**Comment by Konstanius** [comment]
Fixed alongside MineCICD 2.0 Release
See https://github.com/Konstanius/MineCICD/commit/92dbd0e6daf093352b5790524a930f5ce87fbc22 for changes
