### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by pjindras** [Konstanius/MineCICD#4]
Hello, please how to add all files in directory, for example, when I want to import all plugins from plugins
/minecicd add plugins/ import

this returns 0 folders

I need to import the content to github rep.

Thank you.

**Comment by Konstanius** [comment]
Fixed alongside MineCICD 2.0 Release
See https://github.com/Konstanius/MineCICD/commit/92dbd0e6daf093352b5790524a930f5ce87fbc22 for changes
