### ISSUE TITLE
Windows Error

### ISSUE THREAD

**Issue by minster586** [Konstanius/MineCICD#5]
why does windows, show this error `C:"\"mc_servers\Hub\plugins\MineCICD\repo\`
where this item in quotes does not work

01.07 21:08:26 [Server] INFO minster586 issued server command: /cicd clone
01.07 21:08:26 [Server] WARN java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3
01.07 21:08:26 [Server] WARN \plugins\MineCICD\repo
01.07 21:08:26 [Server] WARN ^
01.07 21:08:26 [Server] WARN at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
01.07 21:08:26 [Server] WARN at java.base/java.util.regex.Pattern.escape(Pattern.java:2608)
01.07 21:08:26 [Server] WARN at java.base/java.util.regex.Pattern.atom(Pattern.java:2286)
01.07 21:08:26 [Server] WARN at java.base/java.util.regex.Pattern.sequence(Pattern.java:2210)
01.07 21:08:26 [Server] WARN at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
01.07 21:08:26 [Server] WARN at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
01.07 21:08:26 [Server] WARN at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
01.07 21:08:26 [Server] WARN at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
01.07 21:08:26 [Server] WARN at java.base/java.lang.String.replaceFirst(String.java:2902)
01.07 21:08:26 [Server] WARN at MineCICD-1.3.jar//ml.konstanius.minecicd.FilesManager$5.preVisitDirectory(FilesManager.java:590)
01.07 21:08:26 [Server] WARN at MineCICD-1.3.jar//ml.konstanius.minecicd.FilesManager$5.preVisitDirectory(FilesManager.java:582)
01.07 21:08:26 [Server] WARN at java.base/java.nio.file.Files.walkFileTree(Files.java:2817)
01.07 21:08:26 [Server] WARN at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
01.07 21:08:26 [Server] WARN at MineCICD-1.3.jar//ml.konstanius.minecicd.FilesManager.gitSanitizer(FilesManager.java:582)
01.07 21:08:26 [Server] WARN at MineCICD-1.3.jar//ml.konstanius.minecicd.GitManager.cloneRepo(GitManager.java:78)
01.07 21:08:26 [Server] WARN at MineCICD-1.3.jar//ml.konstanius.minecicd.BaseCommand.lambda$onCommand$1(BaseCommand.java:369)
01.07 21:08:26 [Server] WARN at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
01.07 21:08:26 [Server] WARN at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
01.07 21:08:26 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
01.07 21:08:26 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
01.07 21:08:26 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
01.07 21:09:25 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:842)
01.07 21:09:25 [Server] WARN [PremiumVanish] Task #44 for PremiumVanish v2.7.9 generated an exception
01.07 21:09:25 [Server] INFO com.comphenix.protocol.reflect.FieldAccessException: Field index 2 is out of bounds for length 2
01.07 21:09:25 [Server] INFO at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
01.07 21:09:25 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:316) ~[ProtocolLib.jar:?]
01.07 21:09:25 [Server] INFO at de.myzelyam.premiumvanish.bukkit.features.NightVision.sendAddPotionEffect(NightVision.java:96) ~[PremiumVanish-v279.jar:?]
01.07 21:09:25 [Server] INFO at de.myzelyam.premiumvanish.bukkit.features.NightVision.run(NightVision.java:79) ~[PremiumVanish-v279.jar:?]
01.07 21:09:25 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:09:25 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:09:25 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:09:25 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:09:25 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:09:25 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:10:27 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:10:27 [Server] INFO at java.lang.Thread.run(Thread.java:842) ~[?:?]
01.07 21:10:27 [Server] INFO minster586 issued server command: /cicd reload
01.07 21:10:27 [Server] ERROR Cannot load plugins\MineCICD\config.yml
01.07 21:10:27 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while scanning a double-quoted scalar
01.07 21:10:27 [Server] INFO in 'reader', line 36, column 5:
01.07 21:10:27 [Server] INFO - "\plugins\"
01.07 21:10:27 [Server] INFO ^
01.07 21:10:27 [Server] INFO found unknown escape character p(112)
01.07 21:10:27 [Server] INFO in 'reader', line 36, column 7:
01.07 21:10:27 [Server] INFO - "\plugins\"
01.07 21:10:27 [Server] INFO ^
01.07 21:10:27 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
01.07 21:10:27 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
01.07 21:10:27 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
01.07 21:10:27 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
01.07 21:10:27 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:174) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
01.07 21:10:27 [Server] INFO at ml.konstanius.minecicd.Config.reload(Config.java:34) ~[MineCICD-1.3.jar:?]
01.07 21:10:27 [Server] INFO at ml.konstanius.minecicd.BaseCommand.lambda$onCommand$1(BaseCommand.java:179) ~[MineCICD-1.3.jar:?]
01.07 21:10:27 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:10:27 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:10:27 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
01.07 21:10:27 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
01.07 21:10:27 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
01.07 21:10:27 [Server] INFO at java.lang.Thread.run(Thread.java:842) ~[?:?]
01.07 21:10:27 [Server] INFO Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a double-quoted scalar
01.07 21:10:27 [Server] INFO in 'reader', line 36, column 5:
01.07 21:10:27 [Server] INFO - "\plugins\"
01.07 21:10:27 [Server] INFO ^
01.07 21:10:27 [Server] INFO found unknown escape character p(112)
01.07 21:10:27 [Server] INFO in 'reader', line 36, column 7:
01.07 21:10:27 [Server] INFO - "\plugins\"
01.07 21:10:27 [Server] INFO ^
01.07 21:10:27 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarNonSpaces(ScannerImpl.java:1969) ~[snakeyaml-1.33.jar:?]
01.07 21:10:27 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1902) ~[snakeyaml-1.33.jar:?]
01.07 21:10:27 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1082) ~[snakeyaml-1.33.jar:?]
01.07 21:10:27 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1064) ~[snakeyaml-1.33.jar:?]
01.07 21:10:28 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:452) ~[snakeyaml-1.33.jar:?]
01.07 21:10:28 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:?]
01.07 21:10:28 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntryValue.produce(ParserImpl.java:592) ~[snakeyaml-1.33.jar:?]
01.07 21:10:28 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntryKey.produce(ParserImpl.java:568) ~[snakeyaml-1.33.jar:?]
01.07 21:10:28 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceFirstEntry.produce(ParserImpl.java:555) ~[snakeyaml-1.33.jar:?]
01.07 21:10:28 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
01.07 21:10:28 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?]
01.07 21:10:28 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:265) ~[snakeyaml-1.33.jar:?]
01.07 21:10:29 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:210) ~[snakeyaml-1.33.jar:?]
01.07 21:10:29 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:357) ~[snakeyaml-1.33.jar:?]
01.07 21:10:29 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:336) ~[snakeyaml-1.33.jar:?]
01.07 21:10:29 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:311) ~[snakeyaml-1.33.jar:?]
01.07 21:10:29 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:212) ~[snakeyaml-1.33.jar:?]
01.07 21:10:29 [Server] INFO at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:134) ~[snakeyaml-1.33.jar:?]
01.07 21:10:29 [Server] INFO at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:160) ~[snakeyaml-1.33.jar:?]
01.07 21:10:29 [Server] INFO at org.yaml.snakeyaml.Yaml.compose(Yaml.java:559) ~[snakeyaml-1.33.jar:?]
01.07 21:10:30 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
01.07 21:10:30 [Server] INFO ... 12 more
01.07 21:10:30 [Server] INFO MineCICD started listening on: http://192.168.1.254:8080/minecicd
01.07 21:10:30 [Server] INFO minster586 issued server command: /cicd clone
01.07 21:10:30 [Server] ERROR Token is blank
01.07 21:10:30 [Server] ERROR Repository URL is blank
01.07 21:10:30 [Server] WARN java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3
01.07 21:10:30 [Server] WARN \plugins\MineCICD\repo
01.07 21:10:30 [Server] WARN ^
01.07 21:10:30 [Server] WARN at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
01.07 21:10:30 [Server] WARN at java.base/java.util.regex.Pattern.escape(Pattern.java:2608)
01.07 21:10:30 [Server] WARN at java.base/java.util.regex.Pattern.atom(Pattern.java:2286)
01.07 21:10:30 [Server] WARN at java.base/java.util.regex.Pattern.sequence(Pattern.java:2210)
01.07 21:10:30 [Server] WARN at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
01.07 21:10:30 [Server] WARN at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
01.07 21:10:30 [Server] WARN at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
01.07 21:10:30 [Server] WARN at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
01.07 21:10:30 [Server] WARN at java.base/java.lang.String.replaceFirst(String.java:2902)
01.07 21:10:30 [Server] WARN at MineCICD-1.3.jar//ml.konstanius.minecicd.FilesManager$5.preVisitDirectory(FilesManager.java:590)
01.07 21:10:30 [Server] WARN at MineCICD-1.3.jar//ml.konstanius.minecicd.FilesManager$5.preVisitDirectory(FilesManager.java:582)
01.07 21:10:30 [Server] WARN at java.base/java.nio.file.Files.walkFileTree(Files.java:2817)
01.07 21:10:30 [Server] WARN at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
01.07 21:10:30 [Server] WARN at MineCICD-1.3.jar//ml.konstanius.minecicd.FilesManager.gitSanitizer(FilesManager.java:582)
01.07 21:10:30 [Server] WARN at MineCICD-1.3.jar//ml.konstanius.minecicd.FilesManager.mergeToLocal(FilesManager.java:105)
01.07 21:10:30 [Server] WARN at MineCICD-1.3.jar//ml.konstanius.minecicd.BaseCommand.lambda$onCommand$1(BaseCommand.java:370)
01.07 21:10:30 [Server] WARN at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
01.07 21:11:25 [Server] WARN at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
01.07 21:11:25 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
01.07 21:11:25 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
01.07 21:11:25 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
01.07 21:11:25 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:842)
01.07 21:11:25 [Server] WARN [PremiumVanish] Task #44 for PremiumVanish v2.7.9 generated an exception
01.07 21:11:25 [Server] INFO com.comphenix.protocol.reflect.FieldAccessException: Field index 2 is out of bounds for length 2
01.07 21:11:25 [Server] INFO at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
01.07 21:11:25 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:316) ~[ProtocolLib.jar:?]
01.07 21:11:25 [Server] INFO at de.myzelyam.premiumvanish.bukkit.features.NightVision.sendAddPotionEffect(NightVision.java:96) ~[PremiumVanish-v279.jar:?]
01.07 21:11:25 [Server] INFO at de.myzelyam.premiumvanish.bukkit.features.NightVision.run(NightVision.java:79) ~[PremiumVanish-v279.jar:?]
01.07 21:11:25 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:11:25 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:11:25 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:13:25 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:13:25 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:13:25 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:13:25 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:13:25 [Server] INFO at java.lang.Thread.run(Thread.java:842) ~[?:?]
01.07 21:13:25 [Server] WARN [PremiumVanish] Task #44 for PremiumVanish v2.7.9 generated an exception
01.07 21:13:25 [Server] INFO com.comphenix.protocol.reflect.FieldAccessException: Field index 2 is out of bounds for length 2
01.07 21:13:25 [Server] INFO at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
01.07 21:13:25 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:316) ~[ProtocolLib.jar:?]
01.07 21:13:25 [Server] INFO at de.myzelyam.premiumvanish.bukkit.features.NightVision.sendAddPotionEffect(NightVision.java:96) ~[PremiumVanish-v279.jar:?]
01.07 21:13:25 [Server] INFO at de.myzelyam.premiumvanish.bukkit.features.NightVision.run(NightVision.java:79) ~[PremiumVanish-v279.jar:?]
01.07 21:13:25 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:13:25 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:13:25 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:15:25 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:15:25 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:15:25 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:15:25 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:15:25 [Server] INFO at java.lang.Thread.run(Thread.java:842) ~[?:?]
01.07 21:15:25 [Server] WARN [PremiumVanish] Task #44 for PremiumVanish v2.7.9 generated an exception
01.07 21:15:25 [Server] INFO com.comphenix.protocol.reflect.FieldAccessException: Field index 2 is out of bounds for length 2
01.07 21:15:25 [Server] INFO at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
01.07 21:15:25 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:316) ~[ProtocolLib.jar:?]
01.07 21:15:25 [Server] INFO at de.myzelyam.premiumvanish.bukkit.features.NightVision.sendAddPotionEffect(NightVision.java:96) ~[PremiumVanish-v279.jar:?]
01.07 21:15:25 [Server] INFO at de.myzelyam.premiumvanish.bukkit.features.NightVision.run(NightVision.java:79) ~[PremiumVanish-v279.jar:?]
01.07 21:15:25 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:15:25 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:15:25 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:15:26 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:15:26 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:15:26 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:15:26 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
01.07 21:15:26 [Server] INFO at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Comment by Konstanius** [comment]
Plugin is Linux only. I do not plan on adding Windows support, as this plugin is no longer under development.

**Comment by Konstanius** [comment]
As information for those interested into this issue / plugin, the plugin is currently back under active development and is being rewritten in its entirety.
All issues will be fixed and marked as closed with the new release, which improves stability, compatibility, performance and enables more features.

**Comment by Konstanius** [comment]
Fixed alongside MineCICD 2.0 Release
See https://github.com/Konstanius/MineCICD/commit/92dbd0e6daf093352b5790524a930f5ce87fbc22 for changes
